# Generated by Django 4.0.2 on 2022-02-19 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('slug', models.CharField(max_length=64, unique=True, verbose_name='Слаг')),
                ('force_level', models.FloatField(blank=True, max_length=64, null=True, verbose_name='ФПУ')),
                ('normal_level', models.FloatField(blank=True, max_length=64, null=True, verbose_name='НПУ')),
                ('dead_level', models.FloatField(blank=True, max_length=64, null=True, verbose_name='УМО')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Водохранилище',
                'verbose_name_plural': 'Водохранилища',
                'db_table': 'reservoirs',
            },
        ),
        migrations.CreateModel(
            name='WaterSituation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('level', models.FloatField(verbose_name='УВБ')),
                ('free_capacity', models.FloatField(blank=True, null=True, verbose_name='Свободный объем')),
                ('inflow', models.FloatField(blank=True, null=True, verbose_name='Приток')),
                ('outflow', models.FloatField(blank=True, null=True, verbose_name='Средний сброс')),
                ('spillway', models.FloatField(blank=True, null=True, verbose_name='Холостой сброс')),
                ('reservoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservoirs.reservoir', verbose_name='Водохранилище')),
            ],
            options={
                'verbose_name': 'Гидрологическая обстановка',
                'verbose_name_plural': 'Гидрологическая обстановка',
                'db_table': 'water_situation',
                'unique_together': {('date', 'reservoir_id')},
            },
        ),
    ]
