# Generated by Django 4.0.2 on 2022-02-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('slug', models.CharField(max_length=64, unique=True, verbose_name='Слаг')),
                ('force_level', models.FloatField(blank=True, max_length=64, null=True, verbose_name='ФПУ')),
                ('normal_level', models.FloatField(blank=True, max_length=64, null=True, verbose_name='НПУ')),
                ('dead_level', models.FloatField(blank=True, max_length=64, null=True, verbose_name='УМО')),
            ],
            options={
                'db_table': 'reservoirs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WaterSituation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('level', models.FloatField(verbose_name='УВБ')),
                ('free_capacity', models.FloatField(blank=True, null=True, verbose_name='Свободный объем')),
                ('inflow', models.FloatField(blank=True, null=True, verbose_name='Приток')),
                ('outflow', models.FloatField(blank=True, null=True, verbose_name='Средний сброс')),
                ('spillway', models.FloatField(blank=True, null=True, verbose_name='Холостой сброс')),
            ],
            options={
                'db_table': 'water_situation',
                'managed': False,
            },
        ),
    ]
