# Generated by Django 4.0.2 on 2022-02-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservoirs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservoir',
            name='area',
            field=models.FloatField(blank=True, help_text='Площадь водохранилища в км²', max_length=64, null=True, verbose_name='Площадь'),
        ),
        migrations.AddField(
            model_name='reservoir',
            name='full_volume',
            field=models.FloatField(blank=True, help_text='Полный объем водохранилища в км³', max_length=64, null=True, verbose_name='Полный объем'),
        ),
        migrations.AddField(
            model_name='reservoir',
            name='max_depth',
            field=models.FloatField(blank=True, max_length=64, null=True, verbose_name='Максимальная глубина'),
        ),
        migrations.AddField(
            model_name='reservoir',
            name='useful_volume',
            field=models.FloatField(blank=True, help_text='Полезный объем водохранилища в км³', max_length=64, null=True, verbose_name='Полезный объем'),
        ),
    ]
