# Generated by Django 4.0.4 on 2022-05-17 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservoirs', '0002_reservoir_area_reservoir_full_volume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watersituation',
            name='reservoir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situations', to='reservoirs.reservoir', verbose_name='Водохранилище'),
        ),
    ]
