# Generated by Django 4.0.5 on 2022-06-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservoirs', '0004_alter_watersituation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watersituation',
            name='free_capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Свободный объем'),
        ),
        migrations.AlterField(
            model_name='watersituation',
            name='inflow',
            field=models.IntegerField(blank=True, null=True, verbose_name='Приток'),
        ),
        migrations.AlterField(
            model_name='watersituation',
            name='outflow',
            field=models.IntegerField(blank=True, null=True, verbose_name='Средний сброс'),
        ),
        migrations.AlterField(
            model_name='watersituation',
            name='spillway',
            field=models.IntegerField(blank=True, null=True, verbose_name='Холостой сброс'),
        ),
    ]
