# Generated by Django 4.0.6 on 2023-06-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservoirs', '0006_alter_reservoir_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservoir',
            name='station_name',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Название ГЭС'),
        ),
    ]
