# Generated by Django 4.0.6 on 2024-12-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_geoobject_roshydromet_id'),
        ('reservoirs', '0007_reservoir_station_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservoir',
            name='geo_objects',
            field=models.ManyToManyField(related_name='reservoirs', to='weather.geoobject', verbose_name='Географические объекты'),
        ),
    ]
