# Generated by Django 4.0.6 on 2026-10-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_geoobject_roshydromet_id'),
        ('reservoirs', '0008_reservoir_geo_objects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservoir',
            name='geo_objects',
            field=models.ManyToManyField(blank=True, related_name='reservoirs', to='weather.geoobject', verbose_name='Географические объекты'),
        ),
    ]
