version: '3.5'

services:
  db:
    image: postgres:14
    container_name: reservoirs_db
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file:
      - ../.env
  adminer:
    image: adminer:latest
    container_name: reservoirs_adminer
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - db

networks:
  default:
    name: reservoirs_network
    driver: bridge

volumes:
  postgres:
