version: '3.3'

services:
  db:
    image: postgres:14
    container_name: reservoirs_db
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file:
      - ../.env

networks:
  default:
    name: reservoirs_network
    driver: bridge

volumes:
  postgres:
