# Generated by Django 4.0.4 on 2022-05-10 11:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата/Время')),
                ('temp', models.FloatField(verbose_name='Температура воздуха')),
                ('pressure', models.PositiveSmallIntegerField(verbose_name='Атмосферное давление')),
                ('humidity', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100, message='Влажность не может быть больше 100 %')], verbose_name='Влажность')),
                ('cloudiness', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100, message='Облачность не может быть больше 100 %')], verbose_name='Облачность')),
                ('wind_speed', models.FloatField(verbose_name='Скорость ветра')),
                ('wind_direction', models.PositiveSmallIntegerField(choices=[(0, 'Нет ветра'), (1, 'Северный'), (2, 'Северо-восточный'), (3, 'Восточный'), (4, 'Юго-восточный'), (5, 'Южный'), (6, 'Юго-западный'), (7, 'Западный'), (8, 'Северо-западный')], validators=[django.core.validators.MaxValueValidator(8, message='Направление ветра задается по шкале от 0 до 8')], verbose_name='Направление ветра')),
                ('precipitation', models.FloatField(verbose_name='Осадки')),
                ('is_observable', models.BooleanField(default=False, verbose_name='На основе наблюдений')),
                ('geo_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather', to='weather.geoobject', verbose_name='Географический объект')),
            ],
            options={
                'verbose_name': 'Погода',
                'verbose_name_plural': 'Погода',
                'unique_together': {('date', 'geo_object')},
            },
        ),
    ]
