# Generated by Django 4.0.4 on 2022-05-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoobject',
            name='station_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Номер метеостанции'),
        ),
    ]
