# Generated by Django 4.0.4 on 2022-05-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_geoobject_station_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weather',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='weather',
            constraint=models.UniqueConstraint(fields=('date', 'geo_object'), name='weather_weather_date_geo_object_id'),
        ),
    ]
