# Generated by Django 4.0.6 on 2023-04-02 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_alter_weather_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='wind_direction',
        ),
    ]
