# Generated by Django 4.0.6 on 2023-04-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_remove_weather_wind_direction'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='weather',
            name='weather_weather_date_geo_object_id',
        ),
        migrations.AddConstraint(
            model_name='weather',
            constraint=models.UniqueConstraint(fields=('date', 'geo_object', 'is_observable'), name='date_geo_object_is_observable_unique'),
        ),
    ]
