# Generated by Django 4.0.6 on 2023-04-29 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservoirs', '0006_alter_reservoir_region'),
        ('weather', '0006_remove_weather_weather_weather_date_geo_object_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterSituationPredictor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint', models.FileField(help_text='Файл состояния модели в формате ckpt', upload_to='predictors/checkpoints/', verbose_name='Модель')),
                ('geo_objects', models.ManyToManyField(related_name='predictors', to='weather.geoobject', verbose_name='Географические объекты')),
                ('reservoir', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservoirs.reservoir', verbose_name='Водохранилище')),
            ],
            options={
                'verbose_name': 'Модель гидрологической обстановки',
                'verbose_name_plural': 'Модели гидрологической обстановки',
            },
        ),
        migrations.CreateModel(
            name='WaterSituationForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('inflow', models.IntegerField(verbose_name='Приток')),
                ('forecast_date', models.DateTimeField(auto_now=True, verbose_name='Время составления прогноза')),
                ('reservoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='reservoirs.reservoir', verbose_name='Водохранилище')),
            ],
            options={
                'verbose_name': 'Прогноз гидрологической обстановки',
                'verbose_name_plural': 'Прогнозы гидрологической обстановки',
            },
        ),
        migrations.AddConstraint(
            model_name='watersituationforecast',
            constraint=models.UniqueConstraint(fields=('date', 'reservoir_id'), name='date_reservoir_id_unique_together'),
        ),
    ]
