# Generated by Django 4.0.6 on 2023-05-13 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='watersituationforecast',
            name='date_reservoir_id_unique_together',
        ),
        migrations.RemoveField(
            model_name='watersituationforecast',
            name='reservoir',
        ),
        migrations.AddField(
            model_name='watersituationforecast',
            name='predictor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='predictors.watersituationpredictor', verbose_name='Модель'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='watersituationforecast',
            constraint=models.UniqueConstraint(fields=('date', 'predictor'), name='date_predictor_unique_together'),
        ),
    ]
