# Generated by Django 4.0.6 on 2023-05-13 07:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0002_remove_watersituationforecast_date_reservoir_id_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watersituationpredictor',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, unique=True, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
