# Generated by Django 4.0.6 on 2023-05-13 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservoirs', '0006_alter_reservoir_region'),
        ('predictors', '0003_watersituationpredictor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watersituationpredictor',
            name='reservoir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservoirs.reservoir', verbose_name='Водохранилище'),
        ),
    ]
