# Generated by Django 4.0.6 on 2023-11-26 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservoirs', '0007_reservoir_station_name'),
        ('predictors', '0004_alter_watersituationpredictor_reservoir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watersituationpredictor',
            name='reservoir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictors', to='reservoirs.reservoir', verbose_name='Водохранилище'),
        ),
    ]
